name: newground3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - astropy=6.1.4
  - astropy-iers-data=0.2024.10.14.0.32.55
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cffi=1.16.0
  - clingo=5.6.2
  - gsl=2.7
  - importlib-metadata=8.5.0
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsqlite=3.44.2
  - libstdcxx=14.1.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - ncurses=6.4
  - numpy=2.1.2
  - openssl=3.3.2
  - packaging=24.1
  - pip=24.2
  - pycparser=2.21
  - pyerfa=2.0.1.4
  - python=3.12.1
  - python_abi=3.12
  - pyyaml=6.0.2
  - readline=8.2
  - scipy=1.14.1
  - setuptools=69.0.3
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.42.0
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.20.2
  - pip:
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==23.2.0
      - austin==2016.0.1
      - austin-dist==3.7.0
      - click==8.1.7
      - clingo-dl==1.4.0
      - clingox==1.2.1
      - clingraph==1.1.2
      - clinguin==1.0.1
      - clorm==1.4.2
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - cython==3.0.11
      - fastapi==0.103.2
      - fonttools==4.54.1
      - future-fstrings==1.2.0
      - gala==1.9.2.dev5
      - gprof2dot==2024.6.6
      - h11==0.14.0
      - idna==3.6
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - nvidia-ml-py==12.560.30
      - pillow==10.2.0
      - psutil==6.1.0
      - pycairo==1.27.0
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - pygments==2.18.0
      - pygobject==3.50.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.1
      - referencing==0.33.0
      - rich==13.9.2
      - rpds-py==0.17.1
      - scalene==1.5.45
      - six==1.16.0
      - snakeviz==2.2.0
      - sniffio==1.3.0
      - starlette==0.27.0
      - sympy==1.13.3
      - tornado==6.4.1
      - typing-extensions==4.9.0
      - uvicorn==0.27.1
      - xdot==1.4
